from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView

from apps.api.views import (
    BackupCleanupJobListView,
    BackupCleanupTriggerView,
    BackupDownloadView,
    BackupDownloadProxyView,
    BackupFileListView,
    BackupFullRestoreJobListView,
    BackupFullRestoreTriggerView,
    BackupUploadView,
    BackupJobViewSet,
    BackupLogView,
    BackupPitrJobListView,
    BackupPitrOptionsView,
    BackupPitrPreviewView,
    BackupPitrTriggerView,
    DatabasePitrJobListView,
    DatabasePitrPreviewView,
    DatabasePitrTriggerView,
    BackupRetentionView,
    BusinessAccountListView,
    BusinessPasswordChangeView,
    DashboardView,
    DatabaseDetailView,
    DatabaseExportView,
    DatabaseListView,
    DatabaseMetricsView,
    DatabaseQueryView,
    DatabaseSchemaChangesView,
    DatabaseTableStructureView,
    LoginView,
    MeView,
    MySQLServiceView,
    MySQLSettingsView,
    StorageBackendViewSet,
    SystemAccountListView,
    SystemPasswordChangeView,
)

router = DefaultRouter()
router.register("backups/jobs", BackupJobViewSet, basename="backup-job")
router.register("storages", StorageBackendViewSet, basename="storage")

urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="api-login"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="api-token-refresh"),
    path("auth/me/", MeView.as_view(), name="api-me"),
    path("dashboard/", DashboardView.as_view(), name="api-dashboard"),
    path("databases/", DatabaseListView.as_view(), name="api-databases"),
    path("databases/<str:name>/tables/<str:table>/", DatabaseTableStructureView.as_view(), name="api-database-table"),
    path("databases/<str:name>/schema-changes/", DatabaseSchemaChangesView.as_view(), name="api-database-schema-changes"),
    path("databases/<str:name>/metrics/", DatabaseMetricsView.as_view(), name="api-database-metrics"),
    path("databases/<str:name>/query/", DatabaseQueryView.as_view(), name="api-database-query"),
    path("databases/<str:name>/export/", DatabaseExportView.as_view(), name="api-database-export"),
    path("databases/<str:name>/", DatabaseDetailView.as_view(), name="api-database-detail"),
    path("mysql/settings/", MySQLSettingsView.as_view(), name="api-mysql-settings"),
    path("mysql/service/", MySQLServiceView.as_view(), name="api-mysql-service"),
    path("dts/", include("apps.dts.urls")),
    path("accounts/business/", BusinessAccountListView.as_view(), name="api-business-accounts"),
    path("accounts/system/", SystemAccountListView.as_view(), name="api-system-accounts"),
    path(
        "accounts/business/<str:user>/<str:host>/password/",
        BusinessPasswordChangeView.as_view(),
        name="api-business-password",
    ),
    path(
        "accounts/system/<str:role>/password/",
        SystemPasswordChangeView.as_view(),
        name="api-system-password",
    ),
    path("backups/files/", BackupFileListView.as_view(), name="api-backup-files"),
    path("backups/upload/", BackupUploadView.as_view(), name="api-backup-upload"),
    path("backups/restore/trigger/", BackupFullRestoreTriggerView.as_view(), name="api-backup-restore-trigger"),
    path("backups/restore/jobs/", BackupFullRestoreJobListView.as_view(), name="api-backup-restore-jobs"),
    path("backups/retention/", BackupRetentionView.as_view(), name="api-backup-retention"),
    path("backups/cleanup/jobs/", BackupCleanupJobListView.as_view(), name="api-backup-cleanup-jobs"),
    path("backups/cleanup/trigger/", BackupCleanupTriggerView.as_view(), name="api-backup-cleanup-trigger"),
    path("backups/pitr/options/", BackupPitrOptionsView.as_view(), name="api-backup-pitr-options"),
    path("backups/pitr/preview/", BackupPitrPreviewView.as_view(), name="api-backup-pitr-preview"),
    path("backups/pitr/jobs/", BackupPitrJobListView.as_view(), name="api-backup-pitr-jobs"),
    path("backups/pitr/trigger/", BackupPitrTriggerView.as_view(), name="api-backup-pitr-trigger"),
    path("backups/pitr/database/preview/", DatabasePitrPreviewView.as_view(), name="api-backup-db-pitr-preview"),
    path("backups/pitr/database/jobs/", DatabasePitrJobListView.as_view(), name="api-backup-db-pitr-jobs"),
    path("backups/pitr/database/trigger/", DatabasePitrTriggerView.as_view(), name="api-backup-db-pitr-trigger"),
    path("backups/download/", BackupDownloadView.as_view(), name="api-backup-download"),
    path("backups/download/proxy/", BackupDownloadProxyView.as_view(), name="api-backup-download-proxy"),
    path("backups/log/", BackupLogView.as_view(), name="api-backup-log"),
    path("", include(router.urls)),
]
