# Generated by Django 5.2.14 on 2026-06-01 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('root', 'Root'), ('backup', '备份账号'), ('default_user', '默认业务用户')], max_length=32, unique=True, verbose_name='角色')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password_enc', models.TextField(blank=True, verbose_name='密码（加密）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统凭证',
                'verbose_name_plural': '系统凭证',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('password_change', '修改密码'), ('backup_trigger', '触发备份'), ('storage_create', '创建存储'), ('storage_update', '更新存储'), ('storage_delete', '删除存储'), ('storage_test', '测试存储'), ('credential_sync', '同步凭证'), ('login', '登录')], max_length=64, verbose_name='操作')),
                ('target', models.CharField(blank=True, max_length=255, verbose_name='目标')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
