# Generated by Django 5.2.14 on 2026-06-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('alias', models.CharField(default='s3', max_length=64, verbose_name='MC 别名')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Endpoint')),
                ('access_key_enc', models.TextField(verbose_name='Access Key（加密）')),
                ('secret_key_enc', models.TextField(verbose_name='Secret Key（加密）')),
                ('bucket', models.CharField(default='mysql', max_length=128, verbose_name='Bucket')),
                ('region', models.CharField(default='us-east-1', max_length=64, verbose_name='Region')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='使用 SSL')),
                ('force_path_style', models.BooleanField(default=True, verbose_name='Path Style')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('last_test_at', models.DateTimeField(blank=True, null=True, verbose_name='上次测试时间')),
                ('last_test_ok', models.BooleanField(default=False, verbose_name='上次测试成功')),
                ('last_test_message', models.TextField(blank=True, verbose_name='测试消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '对象存储',
                'verbose_name_plural': '对象存储',
                'ordering': ['name'],
            },
        ),
    ]
